name="Contexto"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.contexto.zip"
iconimage="https://yt3.ggpht.com/ytc/AKedOLTuzV0fQZOdIYisYYt4TOvSyCYgSLss79mX5jXU=s256-c-k-c0x00ffffff-no-rj"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="BlueseJazz"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.music.bluesejazz.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-bluesejazz.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Novelas Sbt"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.novelassbt.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-novelassbt.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="1thek"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.1thek.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-1thek.jpg"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Now Music"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.now_music.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-nowmusic.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="AltaTensao"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.altatensao.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-altatensao.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="BangBang"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.bangbang.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-bangbang.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Despertar"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.despertar.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-despertar.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="DjMag"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.djmag.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-djmag.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Netmovies"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.netmovies.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-netmovies.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="MusicForYou"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.musicforyou.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-musicforyou.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="CanalRicos"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.ricosaddon.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-ricosaddon.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Alok"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.alok.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-alok.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Fatos Nerd"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.fatosnerd.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-fatosnerd.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Kmusic"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.kmusic.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-kmusic.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Mundo Proibido"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.mundoproibido.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-mundoproibido.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Santo RockBar"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.santorockbartv.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-santorockbartv.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Hunter FM"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.hunterfm.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-hunterfm.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Tecmundo"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.tecmundo.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-tecmundo.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"


name="Canal Area51"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.area51canal.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-area51canal.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Radio Tectoy"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.radiotectoy.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-radiotectoy.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"

name="Zoomundo"
url="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/plugin.video.zoomundo.zip"
iconimage="https://raw.githubusercontent.com/kodishmediacenter/kodi19/master/addons/icon-zoomundo.png"
fanart="https://cld.pt/dl/download/16a5f7e8-64d3-49b3-9008-22ba2747dc82/fanart.jpg"
description="São Todos Addons aprovados para uso Bom Streaming a todos"
skin_id="wwwww"
